add_newline = false
format = """$directory$git_branch$git_status $character """

[directory]
truncation_length = 3

[git_branch]
symbol = " "

[character]
success_symbol = "[➜](bold green)"
error_symbol   = "[✗](bold red)"

